name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04  # СТАРАЯ ВЕРСИЯ

    steps:
    - uses: actions/checkout@v4

    - name: Build APK with Buildozer Docker
      run: |
        docker run --rm \
          -v $PWD:/home/user/hostcwd \
          -v buildozer_docker:/home/user/.buildozer \
          czaki/buildozer:latest \
          android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: seabattle
        path: bin/*.apk
        retention-days: 7